### ISSUE TITLE
'PreTrainedTokenizerFast' object has no attribute 'tokenizer'

### ISSUE THREAD

**Issue by schwjustin** [noamgat/lm-format-enforcer#113]
When I use this code, I get the error 'PreTrainedTokenizerFast' object has no attribute 'tokenizer':
```
import tensorrt_llm
from tensorrt_llm.runtime import ModelRunner
from transformers import AutoTokenizer

...

self.tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

...

from lmformatenforcer import JsonSchemaParser
from lmformatenforcer.integrations.trtllm import (
  build_trtllm_logits_processor,
  build_trtlmm_tokenizer_data
)

schema = {
  "type": "object",
  "properties": {
    "answer": {
      "type": "string",
      "title": "Answer"
    },
  },
  "required": ["answer"]
}

parser = JsonSchemaParser(schema)

tokenizer_data = build_trtlmm_tokenizer_data(tokenizer)

logits_processor = build_trtllm_logits_processor(tokenizer_data, parser)
```

**Comment by noamgat** [comment]
I tried applying a fix for a similar issue from a different integration. Can you try it?

`pip install git+https://github.com/noamgat/lm-format-enforcerl.git@bugfix/trtllm-types`

**Comment by noamgat** [comment]
It looks like something in your build setup.
An alternative way to check the fix is to install the normal package from pip, and add your own copy of trtllm.py with the contents of this:
https://github.com/noamgat/lm-format-enforcer/blob/ff5cd86a9f007340ae73e043c419c23ba1438075/lmformatenforcer/integrations/trtllm.py
and then import from there instead of the `from lmformatenforcer.integrations.trtllm` import
