### ISSUE TITLE
Supporting of streaming

### ISSUE THREAD

**Issue by MarcusTXK** [noamgat/lm-format-enforcer#49]
Apologies if this is a silly question. This library works really well in enforcing the output format, thanks alot for creating it! I am trying to make a home assistant, and the response is a json, with various fields, with the important one being the `msg` field, which will be read out to the user as the reply. 

Streaming of the response would allow me to get the `msg` quicker, as it can be read out even while the rest of the json is being generated. Could I check if streaming of `LLamaCPP` is already supported or if it is planned to be supported anytime in the future?

For example, `LLamaIndex` provides the `stream_complete` endpoint to stream the response as it’s being generated rather than waiting for the entire response to be generated (docs [here](https://docs.llamaindex.ai/en/stable/examples/llm/llama_2_llama_cpp.html#start-using-our-llamacpp-llm-abstraction)), which is lost when we pass it into `LMFormatEnforcerPydanticProgram`.

**Comment by noamgat** [comment]
Assuming you are using LlamaIndex, correct?
If so, there are two ways to use LMFormatEnforcer - one is through `LMFormatEnforcerPydanticProgram`, the other is directly using `activate_lm_enforcer` route using existing `LLamaCPP` instances.
See the [regular expression example](https://docs.llamaindex.ai/en/latest/examples/output_parsing/lmformatenforcer_regular_expressions.html) for more information, you can use it with `JsonSchemaParser` instead of `RegexParser` and it should work for `stream_complete` as well.

**Comment by MarcusTXK** [comment]
Okay, thanks alot for pointing me in the right direction!
