### ISSUE TITLE
Plan to support more syntax parsers? Like python

### ISSUE THREAD

**Issue by hoveychen** [noamgat/lm-format-enforcer#5]
It would be nice to support programming language like Python, to plugin into the interpreter-like agents frameworks.

**Comment by noamgat** [comment]
It's possible to implement a `CharacterLevelParser` for python, the question is how deep will the integration be and what the benefit will be. Since python has a lot of code for the LLM to train on, the code that the various LLMs generate is usually legal from a syntactic point of view, but it doesn't always produce the correct output when the code is ran. A format enforcer can not check the correctness of the code being generated.

Is there a use case where you encounter generated python code that does not compile due to syntax errors?

**Comment by hoveychen** [comment]
In our case, we don't intend to guarantee the syntax of python, instead to ensure the output "purely" consist of python. 
Before putting a lot of effort to fine tune, the LLM sometimes say something else to teach us how to do something, instead of directly showing me the code.

**Comment by noamgat** [comment]
I think traditional prompt engineering works better for these cases.
For example, instead of prompting

```
Q: Can you write a python function to add two numbers?
A:
```

Do something like
```
Q: Can you write a python function to add two numbers?
A:
```
'''python

```

**Comment by keyboardAnt** [comment]
For example, adhering to some formatting style without fine-tuning

**Comment by noamgat** [comment]
That is indeed very interesting! That sounds like a lot of work, I won't get to it myself.
If they end up releasing the code (or anyone else implements it), it will probably be possible to implement a `CharacterLevelParser` that wraps it, allowing it to be used with `lm-format-enforcer`.

PRs welcome :)

**Comment by elonen** [comment]
Llamacpp supports BNF-style context free grammars: https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md

Porting this would be very useful for more complicated/custom syntaxes beyond regex or json. Python thouh, is not fully context-free, IIRC, so it would be quite difficult to enforce exactly.
